include "root" {
  path = find_in_parent_folders()
  expose = true
}

generate "backend" {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
    contents = <<EOF
    terraform {
        backend "azurerm" {
            resource_group_name  = "statefiles"
            storage_account_name = "${include.root.locals.projectdetails.name}statefile"
            container_name       = "layer0"
            key                  = "subscription.tfstate"
        }
    }
    EOF
}

terraform {
    source = include.root.locals.sources["subscription"]
}

inputs = {
    billing_account_name = try(include.root.localsprojectdetails.billing_account_name, null)
    enrollment_account_name = try(include.root.localsprojectdetails.enrollment_account_name, null)
    dbg_simulate = try(include.root.locals.projectdetails.dbg_simulate, false)
    subscription_name = try(include.root.locals.subscription_name, "autogenerated_terraform_subscription")
}