locals {
    projectdetails = yamldecode(file(find_in_parent_folders("project.yml")))
}

generate "provider" {
    path = "provider.tf"
    if_exists = "overwrite_terragrunt"
    contents = <<EOF
    provider "azurerm" {
        features {}
        subscription_id = "${local.projectdetails.default_subscription_id}"
    }
EOF
}

generate "backend" {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
    contents = <<EOF
    terraform {
        backend "azurerm" {
            resource_group_name  = "salzburgagstate"
            storage_account_name = "${local.projectdetails.name}sagstate"
            container_name       = "layer0"
            key                  = "terraform.tfstate"
        }
    }
    EOF
}


terraform {
    source = "github.com/bjornhofer/terraform_subscription.git"
}

inputs = {
    billing_account_name = try(projectdetails.billing_account_name, null)
    enrollment_account_name = try(projectdetails.enrollment_account_name, null)
    dbg_simulate = try(local.projectdetails.dbg_simulate, false)
    subscription_name = try(projectdetails.subscription_name, "autogenerated_terraform_subscription")
}